/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "outline-variant": "#c4c6d0",
              "primary-fixed": "#d7e2ff",
              "on-primary-container": "#89a5dd",
              "on-tertiary-container": "#ff7f6d",
              "surface-dim": "#d8dadd",
              "surface-tint": "#415e91",
              "tertiary-container": "#7c0202",
              "on-surface-variant": "#43474f",
              "error-container": "#ffdad6",
              "on-primary-fixed": "#001b3f",
              "secondary-container": "#e2dfde",
              "primary-container": "#1a3a6b",
              "on-tertiary-fixed": "#410000",
              "on-primary-fixed-variant": "#284678",
              "primary": "#002451",
              "inverse-primary": "#abc7ff",
              "background": "#f7f9fc",
              "surface-bright": "#f7f9fc",
              "on-secondary-fixed-variant": "#474746",
              "on-surface": "#191c1e",
              "tertiary-fixed": "#ffdad5",
              "on-secondary-container": "#636262",
              "secondary-fixed-dim": "#c8c6c5",
              "secondary-fixed": "#e5e2e1",
              "surface-container-low": "#f2f4f7",
              "surface-container-lowest": "#ffffff",
              "on-secondary": "#ffffff",
              "error": "#ba1a1a",
              "on-background": "#191c1e",
              "inverse-on-surface": "#eff1f4",
              "surface": "#f7f9fc",
              "on-tertiary-fixed-variant": "#8e130c",
              "outline": "#747780",
              "on-error-container": "#93000a",
              "tertiary-fixed-dim": "#ffb4a9",
              "on-secondary-fixed": "#1b1b1b",
              "on-primary": "#ffffff",
              "primary-fixed-dim": "#abc7ff",
              "on-tertiary": "#ffffff",
              "surface-container-highest": "#e0e3e6",
              "on-error": "#ffffff",
              "surface-container": "#eceef1",
              "tertiary": "#530000",
              "surface-variant": "#e0e3e6",
              "secondary": "#5f5e5e",
              "surface-container-high": "#e6e8eb",
              "inverse-surface": "#2d3133"
      },
      "borderRadius": {
              "none": "0px",
              "DEFAULT": "0px",
              "lg": "0px",
              "xl": "0px",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
